### PR TITLE
Two players can start at different positions

### PR DESCRIPTION
**Pull request by ghost**
still has bit of awkwardness in beginning because position is set to default before being updated to its correct position

### CODE REVIEW

**Comment by allenkim** [comment]
Yea, I was actually thinking of getting rid of the whole prototype stuff and making game visible globally in some kind of script file to make it easier for socketing. But, for now, can you get rid of the npm log file? Then, I'll merge it.

**Comment by ghost** [comment]
I removed it now I think.

What do you mean by getting rid of prototype stuff?

Gautam R.

**Comment by allenkim** [comment]
The prototyping of the different phaser states

**Comment by ghost** [comment]
Do you want it as one html file?

Sent from my BlackBerry 10 smartphone.
From: Allen Kim
Sent: Saturday, November 28, 2015 11:09 PM
To: ackei/missile-warfare
Reply To: ackei/missile-warfare
Cc: gramasu000@citymail.cuny.edu
Subject: Re: [missile-warfare] Two players can start at different positions (#2)

The prototyping of the different phaser states

##

**Comment by allenkim** [comment]
Separate files. We can discuss further in person

**Pull request merged**
